### PR TITLE
Add cmake support

### PR DESCRIPTION
**Pull request by jschueller**
Allows to build for windows

### CODE REVIEW

**Comment by beniz** [comment]
Thanks for this contribution. Could you update the README with instructions for building with cmake before merging ?

**Comment by jschueller** [comment]
@beniz ok

**Comment by beniz** [comment]
Thanks. Please rebase to master, and check whether the tests do complete. Thee last travis report shows all unit tests failing. I would advice against modifying the travis eigen version or anything related to travis here, and to do a dedicated PR.

**Comment by jschueller** [comment]
ok

**Comment by jschueller** [comment]
@beniz, I rebased to master, I'll submit travis changes in another PR, please review.

**Comment by beniz** [comment]
Perfect, thanks for your contribution. FTR, note that the cmake build uses `-O3` optimization with no debug `-g` flag while the original build uses `-O2 -g`.

**Pull request merged**
