### PR TITLE
Moving the header files

### PR DESCRIPTION
**Pull request by phbasler**
Hi @beniz 

Sorry for the long delay, but @jwittbrodt and I finally managed to move the header files to the discussed include/libcmaes structure. 
We testet it with cmake and autogen install and the test functions work. 

Please tell me if something does not work as intendend on your side.

Once this is merged, can you maybe do a small release so we can link to this version with our Code? 

Cheers
Philipp

### CODE REVIEW

**Comment by beniz** [comment]
Thanks @phbasler for the work on this, can you fix the conflicts / rebase and squash commits into a single fix if you don't mind ? I'll then test, merge & release, thanks!

**Comment by phbasler** [comment]
The resolves are fixed. 
Is there a way to squash them in an already existing PR or do I have to open a new one?

**Comment by beniz** [comment]
Great @phbasler you can squash on your branch then force push on, this will update this PR.

**Comment by phbasler** [comment]
@beniz  Like this?

**Comment by beniz** [comment]
@phbasler great, thank you.

**Comment by beniz** [comment]
@phbasler the configure build is broken, at minima it requires having a `libcmaes/cmaes_export.h` dir and file in `src/` and the same in `include/`. Do we really need this `cmaes_export.h` header ?

**Comment by beniz** [comment]
It'd be OK to remove the autotools build later on, in another PR, but at this stage, I'd rather keep it in working state.

**Comment by phbasler** [comment]
@beniz  You only need to `echo "#define CMAES_EXPORT" > include/libcmaes/cmaes_export.h` in the top directory, then the configure build works. With this you don't need to set an env variable in your bash shell

**Comment by beniz** [comment]
Have you tried the build, because it doesn't work for me, some includes are wrong I believe.

**Comment by phbasler** [comment]
I forgot to mention one thing which I did not manage with autogen:
Everyone with a manual created makefile will have to change one small thing for backwards compatibility:
Instead of just including path/to/libcmaes/include they will also have to include path/to/libcmaes/include/libcmaes , then the old code will work. 
If you know any autogen vodoo to get this done automatically I would be happy to adjust

**Comment by beniz** [comment]
OK, thanks for the info, can you update the README so that the `echo` step is the right one ? I'll merge after that. Thanks.

**Comment by phbasler** [comment]
The readme already has the updated echo command. See line 55 of the readme file

**Comment by beniz** [comment]
oops, my apologies, looked at the wrong one.

**Pull request merged**
