### PR TITLE
a little clean up

### PR DESCRIPTION
**Pull request by nikohansen**

### CODE REVIEW

**Comment by beniz** [comment]
I did merge it a little quickly, the pylab.ion() causes the plot to go away when used in simple.py for example.

**Comment by nikohansen** [comment]
To my understanding `ion` prevents the program being stuck until the plot is manually closed. That is, the plot should still be there, maybe not as foremost window. 

If I use `simple.py` in an ipython notebook, I have cases where I get completely stuck without `ion`, as I cannot see/find the plot to be closed to continue.

**Comment by beniz** [comment]
I'm not versed enough with Python and notebooks to comment other than pointing to the problem I see on my machine:
```
python simple.py
```
flashes the plot to the screen and kills it. If I comment out the `pylab.ion()` line, the plot stays in view properly. Maybe we can have `ion()` optional ?

**Comment by nikohansen** [comment]
This happens even though `simple.py` is still running, that is you haven't hit `return` to continue?

Without `ion`, when do you see the print message on the console, before or after closing the figure?

**Comment by beniz** [comment]
> when do you see the print message on the console, before or after closing the figure?

not sure what you mean. The only message I see is:
```
/usr/lib/pymodules/python2.7/matplotlib/scale.py:90: RuntimeWarning: invalid value encountered in less_equal
  mask = a <= 0.0
```
and this is definitely before the window opens.

> that is you haven't hit return to continue?

There's no prompt for continuing, I believe this is because the prompt is in the `__main__` function, not in the call from API.

**Comment by nikohansen** [comment]
I see, sorry, I overlooked that `simple.py` hasn't a main part. Relying on `cma_multiplt` to remain stuck until the window is closed seems not a very clean approach though. Unfortunately, I have currently problems to get the desired behavior regardless of `ion()`. It has always been a little difficult to get all use-cases right with matplotlib. Adding 

```python
if __name__ == "__main__":
    msg = '  --- press return to continue --- '
    try: 
        raw_input(msg) 
    except NameError: 
        input(msg)
```
at the end of `simple.py` should solve at least your problem.

**Comment by beniz** [comment]
Thanks, done.

**Comment by nikohansen** [comment]
FTR, if the above doesn't work, this 
```python
if __name__ == '__main__':
    from matplotlib import pyplot
    print('--- close window to resume ---')
    pyplot.ioff()
    pyplot.show()
```
might do the job.

**Pull request merged**
