### PR TITLE
tests/cma_multiplt.py usable with import

### PR DESCRIPTION
**Pull request by nikohansen**

### CODE REVIEW

**Comment by nikohansen** [comment]
I don't exactly understand why we see the commits from 2014 here, I just meant to push those from  Feb 12 2015.

**Comment by beniz** [comment]
Yes, this is because you may want to create a branch with your fixes on your repo and PR that branch. Otherwise github detects it as an addition to an existing PR. Basically a PR can be understood and defined by two endpoints, yours and that to which you'd like your code to be integrated.

I don't believe it matters too much just now for this one, and I'll try to use it as is.

**Comment by beniz** [comment]
FYI, I don't believe it matters too much as the plot looks fine but I get this error:
```
/usr/lib/pymodules/python2.7/matplotlib/scale.py:90: RuntimeWarning: invalid value encountered in less_equal
  mask = a <= 0.0
```

**Comment by nikohansen** [comment]
I believe this is unrelated to the _changes_ in `cma_multiplt.py`.

**Comment by beniz** [comment]
This has been merged.

**Comment by beniz** [comment]
Ah, just a thingy, when doing PR, it is best to do them against 'dev' branch. In this particular case it didn't matter though.

**Pull request closed without merging**
