### PR TITLE
Fix boost detection

### PR DESCRIPTION
**Pull request by jschueller**
https://github.com/beniz/libcmaes/pull/160 broke it by removing pythonX lib name
but we can have both python-pyXY and pythonX (in that order)
so everyone is happy

### CODE REVIEW

**Comment by jschueller** [comment]
These changes make the Python bindings work on windows.

**Comment by beniz** [comment]
Could you rebase against `master` so that we can see whether the tests are passing ? Thanks.

**Comment by jschueller** [comment]
ok, maybe you want to also merge #167

**Comment by jschueller** [comment]
ready to merge ?

**Comment by beniz** [comment]
Thanks for this improvement!

**Pull request merged**
